package main

import (
	"github.com/joho/godotenv"
	"github.com/prometheus/common/log"

	_ "01cloud-payment/cmd/server/docs" // docs is generated by Swag CLI, you have to import it.
	"01cloud-payment/internal/controllers"
	"01cloud-payment/internal/models"
	"01cloud-payment/internal/util"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

// @title 01cloud-payment
// @version 1.0
// @description 01cloud-payment
// @termsOfService http://swagger.io/terms/
// @contact.name Payment Support
// @contact.email info@01cloud.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
func main() {
	godotenv.Load()
	config, err := util.LoadConfig(".")
	if err != nil {
		log.Fatal("Cannot load config", err)
	}
	conn, err := gorm.Open(config.DBDriver, config.DBSource)
	if err != nil {
		log.Fatal("Cannot connect to db", err)
	}
	store := models.NewDB(conn)
	store.MigrateDB()
	server, err := controllers.NewServer(config, store)
	if err != nil {
		log.Fatal("Cannot create server : ", err)
	}
	server.Run(":8080")
}
